### ISSUE TITLE
Also add inbuilt suppport for pagination.

### ISSUE THREAD

**Issue by ahampriyanshu** [SauravKanchan/NewsAPI#11]
Hi @SauravKanchan , first of all thank you for this wonderfull api:clap:.It would be amazing if you can add inbuilt support for pagination just like``pageSize`` , ``page`` in the original newsapi.I know that newsapi has restrited max ``pageSize``  to 100 articles  but still 10 articles per page  for would be  really nice.

I have built [this](https://gonewz.herokuapp.com) pwa  in golang and tailwind by using your api.Any feedback would mean a lot.

**Comment by SauravKanchan** [comment]
Hi @ahampriyanshu Nice to see you using this API, Your PWA looks awesome. Right now I am busy with other projects and my office work, once I am free I will try to add some sort of pagination in this.

**Comment by ahampriyanshu** [comment]
Thank you.
I'll be looking forward to it.
