### ISSUE TITLE
ValueError: malformed node or string: None

### ISSUE THREAD

**Issue by BencyDaniel** [SauravKanchan/NewsAPI#23]
I get this error on the ---> 21 API_KEYS = literal_eval(os.getenv("API_KEYS")) line and I don't understand why

**Comment by SauravKanchan** [comment]
you have to add .env file your project directory. 

Sample Env file:

```
API_KEYS=["<api_key_1>", "<api_key_2>"] # To fetch the news feed
GITHUB_API_TOKEN=<github_token> # To commit the news feed on github
```
