### ISSUE TITLE
Issue with API

### ISSUE THREAD

**Issue by mahithabsl** [SauravKanchan/NewsAPI#4]
The business category api (https://saurav.tech/NewsAPI/top-headlines/category/business/in.json)is not found. 
Could u please recheck?

**Comment by abhisheksarmah** [comment]
`business` category is not defined in the `CATEGORIES` array

https://github.com/SauravKanchan/NewsAPI/blob/b2e7c331eb852b4f48cdf45d66afd439e84a2af5/main.py#L12

That is why this API is not dumping data from the News API business category.

**Comment by mahithabsl** [comment]
yea ur right!

**Comment by SauravKanchan** [comment]
Added business
