### ISSUE TITLE
How to use it in Retrofit 2

### ISSUE THREAD

**Issue by SyedAtifAli** [SauravKanchan/NewsAPI#6]
Hi owner, I am a beginner developer and only nows retrofit for network calls and fetching data, and I am unable to use this API in retrofit, actually the last param <country_code>.json is giving me a problem so can you add a sample code on how to use your API with the retrofit, currently I am using newspaper but it will expire soon

**Comment by bill41708** [comment]
I got an error
if base64content.decode('utf-8') != data['content'].replace("\n", ""):
KeyError: 'content'
